# Generated by Selenium IDE - Modified with robust error handling
import pytest
import time
import json
import os
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.common.exceptions import TimeoutException, NoSuchElementException, StaleElementReferenceException
from selenium.webdriver.edge.options import Options


class TestUntitled():

    def setup_method(self, method):
        # =========================
        # Microsoft Edge setup (Windows)
        # =========================
        edge_options = Options()
        edge_options.add_argument("--start-maximized")
        # edge_options.add_argument("--headless=new")  # Uncomment if needed
        edge_options.add_argument("--disable-gpu")
        edge_options.add_argument("--disable-infobars")
        edge_options.add_argument("--disable-extensions")

        self.driver = webdriver.Edge(options=edge_options)
        self.vars = {}

        # Load test data from JSON (relative path – Windows safe)
        BASE_DIR = os.path.dirname(os.path.abspath(__file__))
        with open(os.path.join(BASE_DIR, "test_data1.json"), "r", encoding="utf-8") as f:
            self.test_data = json.load(f)

    def teardown_method(self, method):
        self.driver.quit()

    def wait_and_click(self, by, value, timeout=10, retries=3, scroll=True):
        """Helper method to wait for element and click with retry logic"""
        for attempt in range(retries):
            try:
                element = WebDriverWait(self.driver, timeout).until(
                    EC.element_to_be_clickable((by, value))
                )

                if scroll:
                    self.driver.execute_script(
                        "arguments[0].scrollIntoView({behavior:'smooth', block:'center'});",
                        element
                    )
                    time.sleep(0.5)

                try:
                    self.driver.execute_script("arguments[0].click();", element)
                except Exception:
                    element.click()

                return element

            except StaleElementReferenceException:
                if attempt == retries - 1:
                    raise
                time.sleep(1)

    def wait_and_send_keys(self, by, value, keys, timeout=10, retries=3):
        """Helper method to wait for element and send keys with retry logic"""
        for attempt in range(retries):
            try:
                element = WebDriverWait(self.driver, timeout).until(
                    EC.presence_of_element_located((by, value))
                )
                element.clear()
                element.send_keys(keys)
                return element

            except StaleElementReferenceException:
                if attempt == retries - 1:
                    raise
                time.sleep(1)

    def test_untitled(self):
        print("Starting test...")

        # 1 | open |
        self.driver.get("https://www.tangerine.com.au/nbn/nbn-broadband")
        time.sleep(3)

        # 2 | type | address
        self.wait_and_send_keys(By.ID, "autocomplete", self.test_data["address"])
        time.sleep(3)

        # 3 | autocomplete select
        try:
            WebDriverWait(self.driver, 10).until(
                EC.visibility_of_element_located((By.CSS_SELECTOR, ".autocomplete-suggestion"))
            )
            suggestion = self.driver.find_element(By.CSS_SELECTOR, ".autocomplete-suggestion")
            self.driver.execute_script("arguments[0].click();", suggestion)

        except Exception:
            field = self.driver.find_element(By.ID, "autocomplete")
            field.send_keys(Keys.ARROW_DOWN)
            field.send_keys(Keys.ENTER)

        time.sleep(3)

        # 4 | Build Your Plan
        self.wait_and_click(By.LINK_TEXT, "Build Your Plan")
        time.sleep(3)

        # 5 | Select speed
        self.wait_and_click(By.ID, "75_speed")
        time.sleep(2)

        # 5.5 | Popup continue
        try:
            btn = WebDriverWait(self.driver, 10).until(
                EC.element_to_be_clickable((By.ID, "a2g_back_btn"))
            )
            self.driver.execute_script("arguments[0].click();", btn)
        except Exception:
            pass

        time.sleep(2)

        # 6 | Order Now
        self.driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        time.sleep(1)
        self.wait_and_click(By.CSS_SELECTOR, ".mt-2 > #addressordernotfound")
        time.sleep(2)

        # 7 | Agree and Continue
        try:
            self.wait_and_click(
                By.XPATH,
                "//*[@id='modem-select-NBN-not-selected']/div/div[3]/div/a"
            )
        except Exception:
            self.wait_and_click(By.LINK_TEXT, "Agree and Continue")

        time.sleep(3)

        # 8 | Email
        self.wait_and_send_keys(By.ID, "login_email", self.test_data["email"])
        time.sleep(2)

        # 9 | Submit email
        self.wait_and_click(By.ID, "submit_email")
        time.sleep(4)

        # 10–13 | Personal details
        self.wait_and_click(By.ID, "salutation")
        self.wait_and_send_keys(By.ID, "fname", self.test_data["first_name"])
        self.wait_and_send_keys(By.ID, "lname", self.test_data["last_name"])
        self.wait_and_send_keys(By.ID, "mobile", self.test_data["mobile"])

        # 14 | DOB
        dob = WebDriverWait(self.driver, 10).until(
            EC.presence_of_element_located((By.ID, "dob"))
        )
        self.driver.execute_script(
            "arguments[0].value = arguments[1];",
            dob,
            self.test_data["dob"]
        )
        self.driver.execute_script("arguments[0].dispatchEvent(new Event('input'))", dob)
        time.sleep(1)

        # 16 | Dropdown
        dropdown = WebDriverWait(self.driver, 10).until(
            EC.presence_of_element_located((By.ID, "hear_about_us"))
        )
        dropdown.find_element(By.XPATH, "//option[.='--Other--']").click()

        # 17–22 | Remaining steps
        self.wait_and_click(By.CSS_SELECTOR, ".custom-control-label:nth-child(3)")
        self.wait_and_click(By.CSS_SELECTOR, ".contactnext")
        self.wait_and_click(By.ID, "btn-address-transfer")
        self.wait_and_click(By.ID, "btn-transfer-number")
        self.wait_and_click(By.ID, "donate-no")
        self.wait_and_click(By.ID, "btn-address-transfer")

        print("✅ Test completed successfully!")

